# Generated by Django 4.2.3 on 2023-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(default=1, max_length=240, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='nameCompany',
            field=models.CharField(max_length=240, verbose_name='nameCompany'),
        ),
    ]
