import { useState } from "react"
import { CarouselData } from "shared/models/types/CarouselData"

export const useCarousel  = (): { data : CarouselData[]} => {
    const [data, setData] = useState<CarouselData[]>([{content_1 : {title : "Požadavky na uchazeče:", description : '• Vysokoškolské vzdělání. • Věk do 45 let. • Znalost angličtiny a češtiny minimálně na úrovni b2, je žádoucí mít české občanství. • Dobrá schopnost práce s PC a programy jako Word, Excel, PowerPoint atd. • Kompetentní písemný a ústní projev. • Vysoká úroveň sebeorganizace a pozornosti. • Praxe ve firmě prodávající a montuje salar panely výhodou. • Schopnost pracovat v týmu. • Schopnost být vedoucím týmu je vítána. • Odolnost vůči stresu. • Smysl pro humor. • Rozumí trhu nákupu a prodeje solárních panelů v ČR.'},
     content_2 : {title : 'Úkoly:', description: '• Komunikace s klienty online i osobně. • Příprava seznamu potenciálních klientů, smluv, prezentací, obchodních nabídek a rozesílání na seznam. • Údržba programu SoftWare pro transakční obratový doklad a interní výkaznictví. • Předání smluv, faktur a balicích listů účetnímu. • Předpoklad: Vytvořte si vlastní manažerský tým o 2-4 lidech, vyškolte nováčky, najměte nové zástupce.'},
     content_3 : {title : 'Podmínky:', description : '• Pracujte na dálku i v kanceláři. • Příležitost pro neustálé učení a kariérní růst. • Příležitost realizovat se a stát se lídrem směru nebo projektu. • Rozvoj vlastních klientů – z toho provize až 25 % ze zisku + bonusy.'}},
    {content_1 : {title : "Požadavky na uchazeče:", description : '• Vysokoškolské vzdělání. • Věk do 45 let. • Znalost angličtiny a češtiny minimálně na úrovni b2, je žádoucí mít české občanství. • Dobrá schopnost práce s PC a programy jako Word, Excel, PowerPoint atd. • Kompetentní písemný a ústní projev. • Vysoká úroveň sebeorganizace a pozornosti. • Praxe ve firmě prodávající a montuje salar panely výhodou. • Schopnost pracovat v týmu. • Schopnost být vedoucím týmu je vítána. • Odolnost vůči stresu. • Smysl pro humor. • Rozumí trhu nákupu a prodeje solárních panelů v ČR.'},
     content_2 : {title : 'Úkoly:', description: '• Komunikace s klienty online i osobně. • Příprava seznamu potenciálních klientů, smluv, prezentací, obchodních nabídek a rozesílání na seznam. • Údržba programu SoftWare pro transakční obratový doklad a interní výkaznictví. • Předání smluv, faktur a balicích listů účetnímu. • Předpoklad: Vytvořte si vlastní manažerský tým o 2-4 lidech, vyškolte nováčky, najměte nové zástupce.'},
     content_3 : {title : 'Podmínky:', description : '• Pracujte na dálku i v kanceláři. • Příležitost pro neustálé učení a kariérní růst. • Příležitost realizovat se a stát se lídrem směru nebo projektu. • Rozvoj vlastních klientů – z toho provize až 25 % ze zisku + bonusy.'}} ])

     return {data : data}
}